<script setup lang="ts">
import { Head, Link, router } from '@inertiajs/vue3';
import { watchDebounced } from '@vueuse/core';
import { Bookmark, BriefcaseBusiness, Building2, CalendarDays, Code2, MapPin, Sparkles } from 'lucide-vue-next';
import { ref } from 'vue';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { jobSelection as jobSelectionRoute } from '@/routes';
import { show as jobSelectionShow } from '@/routes/job-selection';
import type { WorkJob } from '@/types/laravel-models';

type Filters={keyword?:string;company?:string;industry?:string;position_level?:string;employment_type?:string;location?:string;workplace_type?:string;salary_min?:string;salary_max?:string;date_posted?:string;view?:'all'|'saved'|'applied';sort?:'newest'|'salary_high'|'salary_low'};
type Criterion={label:string;score:number|null;status:string}; type Match={score:number|null;criteria:Criterion[]};
const props=defineProps<{jobs:(WorkJob&{applied:boolean;saved:boolean})[];filters?:Filters;filterOptions:{industries:string[];positionLevels:string[];employmentTypes:string[];workplaceTypes:string[]};matchingResume?:{id:number;title:string}|null;matches?:Record<number,Match>}>();
const keyword=ref(props.filters?.keyword||''),company=ref(props.filters?.company||''),industry=ref(props.filters?.industry||''),positionLevel=ref(props.filters?.position_level||''),employmentType=ref(props.filters?.employment_type||''),location=ref(props.filters?.location||''),workplaceType=ref(props.filters?.workplace_type||''),salaryMin=ref(props.filters?.salary_min||''),salaryMax=ref(props.filters?.salary_max||''),datePosted=ref(props.filters?.date_posted||''),activeView=ref<'all'|'saved'|'applied'>(props.filters?.view||'all'),sort=ref(props.filters?.sort||'newest');
const values=()=>({keyword:keyword.value||undefined,company:company.value||undefined,industry:industry.value||undefined,position_level:positionLevel.value||undefined,employment_type:employmentType.value||undefined,location:location.value||undefined,workplace_type:workplaceType.value||undefined,salary_min:salaryMin.value||undefined,salary_max:salaryMax.value||undefined,date_posted:datePosted.value||undefined,view:activeView.value==='all'?undefined:activeView.value,sort:sort.value==='newest'?undefined:sort.value});
watchDebounced([keyword,company,industry,positionLevel,employmentType,location,workplaceType,salaryMin,salaryMax,datePosted,activeView,sort],()=>router.get(jobSelectionRoute.url(),values(),{preserveState:true,preserveScroll:true,replace:true,only:['jobs','filters','matches','matchingResume']}),{debounce:300,maxWait:1000});
const clearFilters=()=>{keyword.value='';company.value='';industry.value='';positionLevel.value='';employmentType.value='';location.value='';workplaceType.value='';salaryMin.value='';salaryMax.value='';datePosted.value=''};
const toggleSaved=(job:WorkJob&{saved:boolean})=>job.saved?router.delete(`/saved-jobs/${job.id}`,{preserveScroll:true}):router.post(`/saved-jobs/${job.id}`,{},{preserveScroll:true});
const salary=(job:WorkJob)=>{const a=Number(job.salary_start??0),b=Number(job.salary_end??0);if(a<=0&&b<=0)return 'Salary not specified';const f=new Intl.NumberFormat('en-US',{style:'currency',currency:job.salary_currency||'USD',maximumFractionDigits:0});const r=a>0&&b>0?`${f.format(a)}–${f.format(b)}`:f.format(a||b);return job.salary_period?`${r} / ${job.salary_period}`:r};
const posted=(job:WorkJob)=>job.published_at?new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric'}).format(new Date(job.published_at)):'Date not specified';
const isNew=(job:WorkJob)=>!!job.published_at&&Date.now()-new Date(job.published_at).getTime()<=259200000;
const criterionText=(c:Criterion)=>c.status==='not_specified'?'Not specified':c.status==='not_enough_data'?'Not enough data':`${c.score??0}%`;
defineOptions({layout:{breadcrumbs:[{title:'Job Selection',href:jobSelectionRoute()}]}});
</script>

<template><Head title="Job Selection"/><div class="jobflow-page bg-[#F5F7FB]"><div class="jobflow-page-frame">
<header class="mb-6"><div class="flex items-center gap-2"><h1 class="jobflow-page-title">Job Selection</h1><Sparkles class="h-5 w-5 text-[#5267D8]"/></div><p class="mt-2 text-[15px] text-slate-600">Explore active opportunities matched to your profile.</p><p v-if="matchingResume" class="mt-1 text-[13px] text-slate-500">Matched using: <strong class="text-[#0A2E48]">{{matchingResume.title}}</strong></p></header>
<div class="grid gap-6 lg:grid-cols-[270px_minmax(0,1fr)]">
<details class="self-start rounded-2xl border border-[#DCE4EF] bg-white p-5 shadow-sm lg:block" open><summary class="flex cursor-pointer list-none items-center justify-between"><h2 class="text-[18px] font-semibold">Filters</h2><button type="button" class="text-[14px] font-semibold text-[#3157D5] hover:underline" @click.prevent="clearFilters">Clear all</button></summary><div class="mt-5 space-y-3"><Input v-model="keyword" class="h-11 text-[15px]" placeholder="Job title or keyword"/><Input v-model="company" class="h-11 text-[15px]" placeholder="Company"/><select v-model="industry" class="filter-select"><option value="">All industries</option><option v-for="x in filterOptions.industries" :key="x">{{x}}</option></select><select v-model="positionLevel" class="filter-select"><option value="">All position levels</option><option v-for="x in filterOptions.positionLevels" :key="x">{{x}}</option></select><select v-model="employmentType" class="filter-select"><option value="">All employment types</option><option v-for="x in filterOptions.employmentTypes" :key="x">{{x}}</option></select><Input v-model="location" class="h-11 text-[15px]" placeholder="Location"/><select v-model="workplaceType" class="filter-select"><option value="">All work arrangements</option><option v-for="x in filterOptions.workplaceTypes" :key="x">{{x}}</option></select><Input v-model="salaryMin" class="h-11 text-[15px]" type="number" min="0" placeholder="Minimum annual salary"/><Input v-model="salaryMax" class="h-11 text-[15px]" type="number" min="0" placeholder="Maximum annual salary"/><select v-model="datePosted" class="filter-select"><option value="">Any date posted</option><option value="1">Past 24 hours</option><option value="7">Past 7 days</option><option value="30">Past 30 days</option></select></div></details>
<main class="min-w-0 space-y-4"><div class="flex flex-wrap items-center justify-between gap-3"><div class="flex rounded-xl border border-[#DCE4EF] bg-white p-1 shadow-sm"><button v-for="v in ['all','saved','applied'] as const" :key="v" class="rounded-lg px-4 py-2 text-[15px] font-semibold capitalize" :class="activeView===v?'bg-[#051C2E] text-white':'text-slate-600 hover:bg-slate-50'" @click="activeView=v">{{v==='all'?'All Jobs':v}}</button></div><div class="flex items-center gap-3"><strong class="text-[15px]">{{jobs.length}} jobs found</strong><select v-model="sort" class="filter-select !w-auto"><option value="newest">Newest</option><option value="salary_high">Salary: High to Low</option><option value="salary_low">Salary: Low to High</option></select></div></div>
<div v-if="!jobs.length" class="rounded-2xl border border-dashed border-slate-300 bg-white px-6 py-14 text-center"><BriefcaseBusiness class="mx-auto mb-4 h-9 w-9 text-slate-400"/><p class="text-[16px] font-semibold">{{activeView==='saved'?'No saved jobs yet':activeView==='applied'?'No applications yet':'No vacancies match your current filters.'}}</p><Button class="mt-4" variant="outline" @click="activeView==='all'?clearFilters():(activeView='all')">{{activeView==='all'?'Clear filters':'Browse Jobs'}}</Button></div>
<article v-for="job in jobs" :key="job.id" class="rounded-2xl border border-[#DCE4EF] bg-white p-5 shadow-[0_4px_16px_rgba(7,31,73,.045)] transition-all duration-200 hover:-translate-y-0.5 hover:border-[#AEBED2] hover:shadow-[0_9px_24px_rgba(7,31,73,.09)]"><div class="grid gap-5 xl:grid-cols-[minmax(0,1fr)_190px] xl:items-center"><div class="flex min-w-0 items-start gap-4"><div class="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-[#071F49] text-white"><Code2 class="h-5 w-5"/></div><div class="min-w-0"><div class="flex flex-wrap items-center gap-2"><Badge v-if="isNew(job)" variant="outline" class="border-blue-200 bg-blue-50 text-blue-700">New</Badge><h2 class="text-[18px] font-semibold">{{job.title}}</h2></div><p class="mt-1 flex items-center gap-2 text-[14px] text-slate-600"><Building2 class="h-4 w-4"/>{{job.company}}</p><div class="mt-3 flex flex-wrap gap-2"><Badge v-if="job.applied">Applied</Badge><Badge v-if="job.saved" variant="secondary">Saved</Badge><Badge v-if="job.workplace_type" variant="secondary">{{job.workplace_type}}</Badge><Badge v-if="job.position_level" variant="outline">{{job.position_level}}</Badge><Badge v-if="job.industry" variant="outline">{{job.industry}}</Badge></div><div class="mt-4 flex flex-wrap gap-x-6 gap-y-2 text-[14px] text-slate-600"><span class="flex items-center gap-2"><MapPin class="h-4 w-4"/>{{job.location||'Location not specified'}}</span><span class="flex items-center gap-2"><CalendarDays class="h-4 w-4"/>Posted {{posted(job)}}</span></div><p class="mt-3 text-[16px] font-semibold">{{salary(job)}}</p></div></div><div class="flex flex-col gap-3 xl:items-end"><div v-if="matches?.[job.id]" class="text-right"><div class="text-[18px] font-bold" :class="(matches[job.id].score??0)>=70?'text-emerald-700':'text-[#3157D5]'">{{matches[job.id].score===null?'Match unavailable':`${matches[job.id].score}% match`}}</div><details class="mt-1 text-left xl:text-right"><summary class="cursor-pointer text-[13px] font-semibold text-[#3157D5]">Why this matches</summary><div class="mt-3 min-w-[220px] rounded-xl border border-[#DCE4EF] bg-[#F8FAFD] p-3 text-left"><div v-for="c in matches[job.id].criteria" :key="c.label" class="mb-2 last:mb-0"><div class="flex justify-between gap-4 text-[13px]"><span>{{c.label}}</span><strong>{{criterionText(c)}}</strong></div><div v-if="c.status==='available'" class="mt-1 h-1.5 overflow-hidden rounded-full bg-slate-200"><div class="h-full rounded-full bg-[#3157D5]" :style="{width:`${c.score??0}%`}"/></div></div></div></details></div><div class="flex gap-2"><Button variant="outline" class="h-10 w-10 p-0" :aria-label="job.saved?'Remove from saved':'Save vacancy'" @click="toggleSaved(job)"><Bookmark class="h-4 w-4" :class="job.saved&&'fill-current'"/></Button><Button as-child><Link :href="jobSelectionShow.url(job)">{{job.applied?'View application':'View vacancy'}}</Link></Button></div></div></div></article>
</main></div></div></div></template>
<style scoped>.filter-select{width:100%;height:2.75rem;border:1px solid #dce4ef;border-radius:.625rem;background:#fff;padding:0 .75rem;font-size:15px;color:#334155}.filter-select:focus{outline:2px solid rgba(49,87,213,.2);border-color:#3157d5}@media(max-width:1023px){details>summary{min-height:2rem}}</style>
